[package]
name = "sherlock-api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = { version = "0.7.5", features = ["ws"] }
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread", "process"] }
